# Workflow Code: EnthralledOyster_v5    DO NOT REMOVE
# Purpose:
#    Checks out the repository and initiates a checkmarx scan on a schedule,
#    when someone kicks it off manually or when it is triggered by another
#    workflow, like the dotnet CI workflow.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    -  Azure App Service or Function (Core Template)
#    -  npm Package                   (Core Template)
#    -  Nuget Package                 (Core Template)
#    -  On-Prem Service               (Core Template)
#    -  On-Prem Site                  (Core Template)

name: Checkmarx CLI SAST Scan

on:
  # TODO: Verify the triggers that will be used
  workflow_dispatch:
    inputs:
      branch-tag-sha:
        description: The branch, tag or sha of the checkmarx scan should be run against. Leave blank to use workflow branch.
        required: false
  schedule:
    # See the following site for help creating the right cron syntax: https://crontab.guru/
    # The cron job is specified in UTC.
    # 04:05 on Tuesday UTC
    # TODO: If keeping this trigger, change the day/time because they run our self-hosted runners
    - cron: 5 4 * * 2
  repository_dispatch:
    types: [run_checkmarx]
    # Expects a client payload like : { ref: value-of-ref, pr-sha: head sha}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.branch-tag-sha || github.event.client_payload.ref || github.ref }}

env:
  REFERENCE: ${{ github.event.inputs.branch-tag-sha || github.event.client_payload.ref || github.ref_name }}
  RUNNER_URL: ${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}/actions/runs/${{ GITHUB_RUN_ID }}
  TIMEZONE: 'america/denver' # TODO: Verify timezone
  
jobs:
  scan-the-code:
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REFERENCE }}
          
      - name: Add status check to PR
        if: github.event.client_payload.pr-sha != 0
        id: create-check
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;                     
            const response = await github.rest.checks.create({
              owner,
              repo,
              head_sha: '${{ github.event.client_payload.pr-sha }}', 
              name: 'status check - checkmarx',
              status: 'in_progress',
              details_url: '${{ env.RUNNER_URL }}',
              external_id: context.runId.toString(),
              output: {
                title: 'Checkmarx SAST Scan',
                summary: 'Pending',
                text: '${{ env.RUNNER_URL }}'
              }
            });
            return response.data.id;

      - name: Run the Scan
        id: scan
        uses: im-open/checkmarx-cli-sast-scan@v2.0.1
        with:
          checkmarx-server-url: ${{ secrets.CHECKMARX_URL }} # This is an org-level secret
          checkmarx-username: ${{ secrets.CHECKMARX_USERNAME }} # This is an org-level secret
          checkmarx-password: ${{ secrets.CHECKMARX_PASSWORD }} # This is an org-level secret
          team: 'CxServer\SP\Company\Users\BDA_IndividualMarketplace\BDAOutSourceTeamCity' # Same for all IM scans

          # TODO: Add your App name and optional project type.
          # Required Format: IndividualMarketplace.[projectName].[optional-project-type]
          # Examples: (IndividualMarketplace.1UP or IndividualMarketplace.Shopping.Mfe)
          # If you have an existing scan, view the checkmarx build step in TeamCity to find this value in the 'Checkmarx Project Name' field.
          project: 'IndividualMarketplace.'

          # TODO: Replace with any files or folders that need to be excluded from the scan.
          # Default list and format at https://github.com/im-open/checkmarx-cli-sast-scan/tree/main#excluding-files-and-folders
          # If you have an existing scan, view the checkmarx build step in TeamCity to see if there were additional exclusions added.
          # exclude-paths: ''

          # The following are default values for each available input.
          # report-name: 'CheckmarxSASTResults.pdf'
          # sast-high: 0    # This cannot exceed 0 according to our standards
          # sast-medium: 4  # This cannot exceed 4 according to our standards
          # sast-low: 11    # This cannot exceed 11 according to our standards
          # break-build: true
          # comment: '${{ github.workflow }} run #${{ github.run_number }} on branch ${{ github.ref }}.'
          # checkmarx-cli-version: 1.1.5

      - name: Upload the PDF Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Checkmarx Report
          path: ${{ steps.scan.outputs.report-path }}
          
      - name: Complete status check on PR
        if: always() && steps.create-check.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;            
            await github.rest.checks.update({
              owner: owner,
              repo: repo,
              check_run_id: '${{ steps.create-check.outputs.result }}', 
              completed_at: new Date().toISOString(),
              status: 'completed',
              conclusion: '${{ (steps.scan.outcome == 'success' && 'success') || 'action_required' }}',
              output: {
                title: 'Checkmarx SAST Scan',
                summary: 'This security scan completed.',
                text: `See [PDF Report](${{ env.RUNNER_URL }}) for results.`,
              }
            });
          
      - name: Send Status to Teams
        if: failure() && github.event.client_payload.pr-sha == 0 && secrets.MS_TEAMS_URI != 0
        uses: im-open/post-status-to-teams-action@v1.1.2
        with:
          title: Checkmarx Security Analysis
          workflow-status: ${{ steps.conclusion.outputs.workflow_conclusion }}
          workflow-type: Deploy
          teams-uri: ${{ secrets.MS_TEAMS_URI }} # This is a repo-level secret (unless 'environment:' has been added to this job)
          timezone: ${{ env.TIMEZONE }}
          custom-facts: |
            [
              { "name": "Actor", "value": "${{ github.event.client_payload.actor || github.actor }}" }
            ]
